#!/bin/bash
#: Description: print Hello and the first command-line argument
printf "Hello, %s!\n" "$1"

animal_1=dog
animal_2=cat
animal_3=dogcat

printf "%s\n%s\n%s\n" $animal_1 $animal_2 $animal_3


