#!/bin/bash
# this is a comment
echo "Hello World" # this is a comment

#system variables

echo Our shell name is $BASH
echo Our shell version name is $BASH_VERSION
echo Our home directory is$HOME
echo Our current working directory is $PWD



#user variables

name=Mark
echo The name is $name

val=10
echo value $val
